In [1]:
import pandas as pd

### DataFrames
#### 1. pd.DataFrame()
#### 2. Heterogenous
#### 3. Ordered
#### 4. Mutable, Size - Mutable
#### 5. Duplication Allowed
#### 6. Customizable indexing row and columns names

In [3]:
df = pd.DataFrame([[101, 'Shruti', 50000], 
                    [102, 'Akshara', 40000], 
                    [103, 'Nilesh', 60000]],
                   columns = ['ID', 'NAME', 'SALARY'])

In [4]:
df

    ID     NAME  SALARY
0  101   Shruti   50000
1  102  Akshara   40000
2  103   Nilesh   60000

In [5]:
df.set_index('ID')
df

    ID     NAME  SALARY
0  101   Shruti   50000
1  102  Akshara   40000
2  103   Nilesh   60000

In [6]:
df2 = pd.DataFrame({'ID' : [101, 102, 103, 104],
                    'NAME' : ['Sumit', 'Priya', 'Anita', 'Supriya'],
                    'SALARY' : [30000, 40000, 50000,  60000]})
df2

    ID     NAME  SALARY
0  101    Sumit   30000
1  102    Priya   40000
2  103    Anita   50000
3  104  Supriya   60000

In [7]:
dataset = pd.read_csv("D:/Dataset/tips.csv")

In [8]:
dataset

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]