In [1]:
import pandas as pd

In [5]:
df1 = pd.DataFrame({'ID' : [101, 102, 103, 104],
                    'NAME' : ['Sumit', 'Priya', 'Anita', 'Supriya'],
                    'AGE' : [34, 56, 55,  29]})

In [6]:
df1

    ID     NAME  AGE
0  101    Sumit   34
1  102    Priya   56
2  103    Anita   55
3  104  Supriya   29

In [7]:
df2 = pd.DataFrame({'ID' : [104, 105, 106],
                    'NAME' : ['Rutu', 'Piyu', 'Pari'],
                    'AGE' : [39, 100, 49]})
df2

    ID  NAME  AGE
0  104  Rutu   39
1  105  Piyu  100
2  106  Pari   49

In [8]:
pd.concat([df1,df2])

    ID     NAME  AGE
0  101    Sumit   34
1  102    Priya   56
2  103    Anita   55
3  104  Supriya   29
0  104     Rutu   39
1  105     Piyu  100
2  106     Pari   49

In [11]:
df3 = pd.DataFrame({'ID' : [105, 106, 107],
                    'NAME' : ['Rutu', 'Piyu', 'Pari'],
                    'SAL' : [39, 100, 49]})
df3

    ID  NAME  SAL
0  105  Rutu   39
1  106  Piyu  100
2  107  Pari   49

In [12]:
pd.concat([df1,df3])

    ID     NAME   AGE    SAL
0  101    Sumit  34.0    NaN
1  102    Priya  56.0    NaN
2  103    Anita  55.0    NaN
3  104  Supriya  29.0    NaN
0  105     Rutu   NaN   39.0
1  106     Piyu   NaN  100.0
2  107     Pari   NaN   49.0

In [13]:
df4 = pd.DataFrame({'ADDRESS' : ['Pune', 'Mumbai', 'Chennai', 'Kashmir'],
                    'DEPT' : ['IT', 'DA', 'DS', 'AI/ML'],
                    'SAL' : [39000, 100000, 49000, 45000]})
df4

   ADDRESS   DEPT     SAL
0     Pune     IT   39000
1   Mumbai     DA  100000
2  Chennai     DS   49000
3  Kashmir  AI/ML   45000

In [14]:
df1

    ID     NAME  AGE
0  101    Sumit   34
1  102    Priya   56
2  103    Anita   55
3  104  Supriya   29

In [15]:
pd.concat([df1, df4], axis = 1)

    ID     NAME  AGE  ADDRESS   DEPT     SAL
0  101    Sumit   34     Pune     IT   39000
1  102    Priya   56   Mumbai     DA  100000
2  103    Anita   55  Chennai     DS   49000
3  104  Supriya   29  Kashmir  AI/ML   45000

In [26]:
emp = pd.DataFrame({'ID' : [101, 102, 103, 104],
                    'NAME' : ['Sumit', 'Priya', 'Anita', 'Supriya'],
                    'AGE' : [34, 56, 55,  29],
                     'DID': [1, 3, 2, 5]})
emp

    ID     NAME  AGE  DID
0  101    Sumit   34    1
1  102    Priya   56    3
2  103    Anita   55    2
3  104  Supriya   29    5

In [27]:
dept = pd.DataFrame({'DID':[1,2,3,4],
                     'DNAME': ['IT', 'Admin', 'HR', 'Sales']})

In [28]:
dept

   DID  DNAME
0    1     IT
1    2  Admin
2    3     HR
3    4  Sales

In [29]:
pd.merge(emp, dept)

    ID   NAME  AGE  DID  DNAME
0  101  Sumit   34    1     IT
1  102  Priya   56    3     HR
2  103  Anita   55    2  Admin

In [31]:
dept2 = pd.DataFrame({'ID':[1,2,3,4],
                     'DNAME': ['IT', 'Admin', 'HR', 'Sales']})
dept2

   ID  DNAME
0   1     IT
1   2  Admin
2   3     HR
3   4  Sales

In [32]:
pd.merge(emp, dept2)

Empty DataFrame
Columns: [ID, NAME, AGE, DID, DNAME]
Index: []

In [33]:
pd.merge(emp, dept2, left_on = 'DID', right_on = 'ID')

   ID_x   NAME  AGE  DID  ID_y  DNAME
0   101  Sumit   34    1     1     IT
1   102  Priya   56    3     3     HR
2   103  Anita   55    2     2  Admin

In [34]:
pd.merge(emp, dept, how='left')

    ID     NAME  AGE  DID  DNAME
0  101    Sumit   34    1     IT
1  102    Priya   56    3     HR
2  103    Anita   55    2  Admin
3  104  Supriya   29    5    NaN

In [35]:
pd.merge(emp, dept, how='right')

      ID   NAME   AGE  DID  DNAME
0  101.0  Sumit  34.0    1     IT
1  103.0  Anita  55.0    2  Admin
2  102.0  Priya  56.0    3     HR
3    NaN    NaN   NaN    4  Sales

In [36]:
pd.merge(emp, dept, how='outer')

      ID     NAME   AGE  DID  DNAME
0  101.0    Sumit  34.0    1     IT
1  103.0    Anita  55.0    2  Admin
2  102.0    Priya  56.0    3     HR
3    NaN      NaN   NaN    4  Sales
4  104.0  Supriya  29.0    5    NaN