In [1]:
import pandas as pd

In [5]:
df = pd.DataFrame({'ID' : [101, 102, 103, 104],
                    'NAME' : ['Sumit', 'Priya', 'Anita', 'Supriya'],
                    'SALARY' : [30000, 40000, 50000,  60000]})

In [6]:
df

    ID     NAME  SALARY
0  101    Sumit   30000
1  102    Priya   40000
2  103    Anita   50000
3  104  Supriya   60000

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      4 non-null      int64
 1   NAME    4 non-null      str
 2   SALARY  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [8]:
df.describe()

               ID        SALARY
count    4.000000      4.000000
mean   102.500000  45000.000000
std      1.290994  12909.944487
min    101.000000  30000.000000
25%    101.750000  37500.000000
50%    102.500000  45000.000000
75%    103.250000  52500.000000
max    104.000000  60000.000000

In [9]:
df['ID']

0    101
1    102
2    103
3    104
Name: ID, dtype: int64

In [10]:
df['SALARY']> 20000

0    True
1    True
2    True
3    True
Name: SALARY, dtype: bool

In [12]:
df['SALARY']> 40000

0    False
1    False
2     True
3     True
Name: SALARY, dtype: bool

In [14]:
df[df['SALARY']> 40000]

    ID     NAME  SALARY
2  103    Anita   50000
3  104  Supriya   60000

In [15]:
df

    ID     NAME  SALARY
0  101    Sumit   30000
1  102    Priya   40000
2  103    Anita   50000
3  104  Supriya   60000

In [16]:
df.loc[df['SALARY'] < 35000, 'SALARY'] = 35000          # loc iloc - change in original location          ### we can replace outlier using this

In [17]:
df                                                 # loc - cloumn ka name pata hai tab use krte hai

    ID     NAME  SALARY
0  101    Sumit   35000
1  102    Priya   40000
2  103    Anita   50000
3  104  Supriya   60000

In [21]:
df.loc[[0,2]]

    ID   NAME  SALARY
0  101  Sumit   35000
2  103  Anita   50000

In [22]:
df.loc[[0,2], 'SALARY']

0    35000
2    50000
Name: SALARY, dtype: int64

In [24]:
df.loc[[0,2], ['NAME', 'SALARY']]

    NAME  SALARY
0  Sumit   35000
2  Anita   50000

In [27]:
df.loc[[True, False, True, False]]

    ID   NAME  SALARY
0  101  Sumit   35000
2  103  Anita   50000

In [28]:
df.iloc[0]

ID          101
NAME      Sumit
SALARY    35000
Name: 0, dtype: object

In [20]:
df.iloc[:, 0]                            # iolc - index pata rahta hai tab use karte hai

0    101
1    102
2    103
3    104
Name: ID, dtype: int64

In [29]:
df.iloc[:, 0:2]

    ID     NAME
0  101    Sumit
1  102    Priya
2  103    Anita
3  104  Supriya

In [31]:
df.iloc[:, [0,2]]

    ID  SALARY
0  101   35000
1  102   40000
2  103   50000
3  104   60000

In [32]:
df.replace({40000:45000, 50000:55000})         # dont change in original

    ID     NAME  SALARY
0  101    Sumit   35000
1  102    Priya   45000
2  103    Anita   55000
3  104  Supriya   60000

In [33]:
df

    ID     NAME  SALARY
0  101    Sumit   35000
1  102    Priya   40000
2  103    Anita   50000
3  104  Supriya   60000

### Replace value in Original
#### 1. inplace  - df.replace({40000:45000, 50000:55000}, inplace = True) 
#### 2. df = df.replace({40000:45000, 50000:55000}) 
#### 2. df['SALARY'].replace({40000:45000, 50000:55000})

In [37]:
df['SALARY'].replace({40000:45000, 50000:55000})

0    35000
1    45000
2    55000
3    60000
Name: SALARY, dtype: int64

In [38]:
df

    ID     NAME  SALARY
0  101    Sumit   35000
1  102    Priya   45000
2  103    Anita   55000
3  104  Supriya   60000

In [35]:
df['SALARY'] = df['SALARY'].replace({40000:45000, 50000:55000})           # change in Original ,  2nd technique
                                                                          # 1st - inplace

In [36]:
df

    ID     NAME  SALARY
0  101    Sumit   35000
1  102    Priya   45000
2  103    Anita   55000
3  104  Supriya   60000

### Adding Column

In [39]:
df['Address'] = ['Pune', 'Mumbai', 'Chennai', 'Delhi']          # if value exist - update, if not exist - add
df

    ID     NAME  SALARY  Address
0  101    Sumit   35000     Pune
1  102    Priya   45000   Mumbai
2  103    Anita   55000  Chennai
3  104  Supriya   60000    Delhi

In [40]:
df.insert(2, 'AGE', [21, 22,23,24])
df

    ID     NAME  AGE  SALARY  Address
0  101    Sumit   21   35000     Pune
1  102    Priya   22   45000   Mumbai
2  103    Anita   23   55000  Chennai
3  104  Supriya   24   60000    Delhi

### Adding Rows

In [41]:
len(df)

4

In [45]:
df.loc[len(df)] = [105, 'Gauri', 16, 60000, 'Nagpur']

In [46]:
df

    ID     NAME  AGE  SALARY  Address
0  101    Sumit   21   35000     Pune
1  102    Priya   22   45000   Mumbai
2  103    Anita   23   55000  Chennai
3  104  Supriya   24   60000    Delhi
4  105    Gauri   16   60000   Nagpur

In [50]:
df.loc[df['ID'] == 102, 'SALARY'] = 30000
df

    ID     NAME  AGE  SALARY  Address
0  101    Sumit   21   35000     Pune
1  102    Priya   22   30000   Mumbai
2  103    Anita   23   55000  Chennai
3  104  Supriya   24   60000    Delhi
4  105    Gauri   16   60000   Nagpur

In [51]:
df.loc[df['AGE']> 22, 'NAME']

2      Anita
3    Supriya
Name: NAME, dtype: str

In [52]:
df[df['AGE']> 22]['NAME']

2      Anita
3    Supriya
Name: NAME, dtype: str

In [57]:
df[(df['AGE']> 22) & (df['SALARY']>35000)]

    ID     NAME  AGE  SALARY  Address
2  103    Anita   23   55000  Chennai
3  104  Supriya   24   60000    Delhi

In [58]:
df[(df['AGE']> 22) & (df['SALARY']>35000)]['NAME']

2      Anita
3    Supriya
Name: NAME, dtype: str

In [59]:
df.drop(3)

    ID   NAME  AGE  SALARY  Address
0  101  Sumit   21   35000     Pune
1  102  Priya   22   30000   Mumbai
2  103  Anita   23   55000  Chennai
4  105  Gauri   16   60000   Nagpur

In [60]:
df

    ID     NAME  AGE  SALARY  Address
0  101    Sumit   21   35000     Pune
1  102    Priya   22   30000   Mumbai
2  103    Anita   23   55000  Chennai
3  104  Supriya   24   60000    Delhi
4  105    Gauri   16   60000   Nagpur

In [61]:
df.drop([0, 2, 3])

    ID   NAME  AGE  SALARY Address
1  102  Priya   22   30000  Mumbai
4  105  Gauri   16   60000  Nagpur

In [62]:
df

    ID     NAME  AGE  SALARY  Address
0  101    Sumit   21   35000     Pune
1  102    Priya   22   30000   Mumbai
2  103    Anita   23   55000  Chennai
3  104  Supriya   24   60000    Delhi
4  105    Gauri   16   60000   Nagpur

In [63]:
df.drop('AGE', axis = 1)                      # axis = 1      pura column delete hoga

    ID     NAME  SALARY  Address
0  101    Sumit   35000     Pune
1  102    Priya   30000   Mumbai
2  103    Anita   55000  Chennai
3  104  Supriya   60000    Delhi
4  105    Gauri   60000   Nagpur

In [64]:
df.drop(['ID', 'Address'], axis = 1)                  # original me change nahi hoga,    if change needed then use inplace

      NAME  AGE  SALARY
0    Sumit   21   35000
1    Priya   22   30000
2    Anita   23   55000
3  Supriya   24   60000
4    Gauri   16   60000

In [65]:
data = pd.read_csv("D:/Dataset/student_10.csv")

In [68]:
data

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [69]:
data.isna().sum()

Date          0
Student ID    3
Class         0
Study hrs     2
Percentage    3
dtype: int64

In [66]:
data.dropna()                    # if axis is not given - row remove

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
6  09-07-2021      1007.0     12        4.0        80.0
9  12-07-2021      1010.0     12        6.0        85.0

In [67]:
data.dropna( axis = 1)                 # if axis is given - column remove

         Date  Class
0  01-07-2021     10
1  02-07-2021     10
2  03-07-2021     10
3  06-07-2021     11
4  07-07-2021     11
5  08-07-2021     11
6  09-07-2021     12
7  10-07-2021     12
8  11-07-2021     12
9  12-07-2021     12

### Numeric value - replace with             
#### 1. mean
#### 2, median  - center 
 
### Categorical - Text value - string  - replace with
#### 1. mode - most occured element

null values ko replace karne ke liye central tendancy use karte hai(mean, median, mode)

In [71]:
mean = data['Study hrs'].mean()
mean

np.float64(4.375)

In [72]:
data['Study hrs'].fillna(mean)           # null values ke jagah mean values jayegi,    but not change in original

0     2.000
1     6.000
2     3.000
3     0.000
4     4.000
5    10.000
6     4.000
7     4.375
8     4.375
9     6.000
Name: Study hrs, dtype: float64

In [73]:
data

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [74]:
data.ffill()

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021      1002.0     10        3.0        60.0
3  06-07-2021      1002.0     11        0.0        60.0
4  07-07-2021      1005.0     11        4.0        60.0
5  08-07-2021      1005.0     11       10.0        60.0
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        4.0        90.0
8  11-07-2021      1009.0     12        4.0        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [75]:
data.bfill()

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021      1005.0     10        3.0        60.0
3  06-07-2021      1005.0     11        0.0        80.0
4  07-07-2021      1005.0     11        4.0        80.0
5  08-07-2021      1007.0     11       10.0        80.0
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        6.0        90.0
8  11-07-2021      1009.0     12        6.0        60.0
9  12-07-2021      1010.0     12        6.0        85.0