In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("D:/Dataset/student_10.csv")

In [37]:
data

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [3]:
data.info() # return - shape(row,colums), null value, datatype

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        10 non-null     str
 1   Student ID  7 non-null      float64
 2   Class       10 non-null     int64
 3   Study hrs   8 non-null      float64
 4   Percentage  7 non-null      float64
dtypes: float64(3), int64(1), str(1)
memory usage: 532.0 bytes

In [4]:
data.describe()  # return - statistical analysis (mean, median, min, max, outlier hai ya nahi)

        Student ID      Class  Study hrs  Percentage
count     7.000000  10.000000   8.000000    7.000000
mean   1006.000000  11.100000   4.375000   72.142857
std       3.464102   0.875595   3.020761   15.236235
min    1001.000000  10.000000   0.000000   50.000000
25%    1003.500000  10.250000   2.750000   60.000000
50%    1007.000000  11.000000   4.000000   80.000000
75%    1008.500000  12.000000   6.000000   82.500000
max    1010.000000  12.000000  10.000000   90.000000

In [5]:
data.shape # tells how many rows and column     # attribute - state and behaviours

(10, 5)

In [6]:
type(data)

pandas.DataFrame

In [7]:
data.size

50

In [8]:
data.head()  # return starting 5 records by default

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN

In [9]:
data.head(3)

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0

In [10]:
data.tail()    # return last 5 records

         Date  Student ID  Class  Study hrs  Percentage
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [11]:
data.tail(3)

         Date  Student ID  Class  Study hrs  Percentage
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [12]:
data.isna()    # true = null    ### Every column me kitne null value hai

    Date  Student ID  Class  Study hrs  Percentage
0  False       False  False      False       False
1  False       False  False      False       False
2  False        True  False      False       False
3  False        True  False      False        True
4  False       False  False      False        True
5  False        True  False      False        True
6  False       False  False      False       False
7  False       False  False       True       False
8  False       False  False       True       False
9  False       False  False      False       False

In [13]:
data.isna().sum()   # .sum means only true values ki summation karega

Date          0
Student ID    3
Class         0
Study hrs     2
Percentage    3
dtype: int64

In [14]:
data.dropna()    # Remove null values but, original me change nahi hoga

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
6  09-07-2021      1007.0     12        4.0        80.0
9  12-07-2021      1010.0     12        6.0        85.0

In [15]:
data.dropna(axis = 1)

         Date  Class
0  01-07-2021     10
1  02-07-2021     10
2  03-07-2021     10
3  06-07-2021     11
4  07-07-2021     11
5  08-07-2021     11
6  09-07-2021     12
7  10-07-2021     12
8  11-07-2021     12
9  12-07-2021     12

In [16]:
data  # original stay as it is

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [21]:
data.dropna(inplace = True, axis = 1)   # remove null value in original
data                                    # Original data me change hota hai

         Date  Class
0  01-07-2021     10
1  02-07-2021     10
2  03-07-2021     10
3  06-07-2021     11
4  07-07-2021     11
5  08-07-2021     11
6  09-07-2021     12
7  10-07-2021     12
8  11-07-2021     12
9  12-07-2021     12

In [33]:
data

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [22]:
data = pd.read_csv("D:/Dataset/student_10.csv")

In [23]:
data

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [34]:
data.isna().sum()

Date          0
Student ID    3
Class         0
Study hrs     2
Percentage    3
dtype: int64

In [24]:
data['Class']    #  kisi 1 column ko acces kr sakte hai

0    10
1    10
2    10
3    11
4    11
5    11
6    12
7    12
8    12
9    12
Name: Class, dtype: int64

In [35]:
data['Class'].mean()

np.float64(11.1)

In [25]:
data['Class'].sum()

np.int64(111)

In [26]:
data['Class'].unique()    # check ub=nique values

array([10, 11, 12])

In [27]:
data['Class'].value_counts()          # return count of unique values

Class
12    4
10    3
11    3
Name: count, dtype: int64

In [28]:
data.columns

Index(['Date', 'Student ID', 'Class', 'Study hrs', 'Percentage'], dtype='str')

In [29]:
data['Study hrs']

0     2.0
1     6.0
2     3.0
3     0.0
4     4.0
5    10.0
6     4.0
7     NaN
8     NaN
9     6.0
Name: Study hrs, dtype: float64

In [30]:
data['Study hrs'] > 4.0

0    False
1     True
2    False
3    False
4    False
5     True
6    False
7    False
8    False
9     True
Name: Study hrs, dtype: bool

In [31]:
data[data['Study hrs'] > 4.0 ]           # filtering techniques         # pura record format me dega
# data[condition]  condition True rahi wo hi record print karega

         Date  Student ID  Class  Study hrs  Percentage
1  02-07-2021      1002.0     10        6.0        80.0
5  08-07-2021         NaN     11       10.0         NaN
9  12-07-2021      1010.0     12        6.0        85.0

In [32]:
df2 = data[data['Study hrs'] > 4.0 ] 
df2

         Date  Student ID  Class  Study hrs  Percentage
1  02-07-2021      1002.0     10        6.0        80.0
5  08-07-2021         NaN     11       10.0         NaN
9  12-07-2021      1010.0     12        6.0        85.0

In [36]:
data['Study hrs'].agg(['min', 'max', 'sum'])       # aggrigate fumction

min     0.0
max    10.0
sum    35.0
Name: Study hrs, dtype: float64